//! 内置广告/追踪器域名列表。
//!
//! 来源：EasyList + Peter Lowe Ad Server List 精选。

/// 内置广告/追踪器域名列表（精选常见域名，完整列表约 3500 个）。
///
/// 来源：EasyList + Peter Lowe's Ad Server List 精选。
/// 此处包含最常见的 ~200 个域名作为核心列表。
pub static AD_DOMAINS: &[&str] = &[
    // Google Ads/Analytics
    "doubleclick.net",
    "googlesyndication.com",
    "googleadservices.com",
    "google-analytics.com",
    "googletagmanager.com",
    "googletagservices.com",
    "adservice.google.com",
    "pagead2.googlesyndication.com",
    // Facebook/Meta
    "facebook.net",
    "fbcdn.net",
    "connect.facebook.net",
    // Ad Networks
    "adnxs.com",
    "adsrvr.org",
    "adform.net",
    "adcolony.com",
    "admob.com",
    "adroll.com",
    "adtech.de",
    "adtechus.com",
    "advertising.com",
    "adzerk.net",
    "appnexus.com",
    "buysellads.com",
    "carbonads.com",
    "casalemedia.com",
    "chitika.net",
    "contextweb.com",
    "conversantmedia.com",
    "criteo.com",
    "criteo.net",
    "dotomi.com",
    "exponential.com",
    "indexexchange.com",
    "infolinks.com",
    "inner-active.com",
    "integralads.com",
    "intentiq.com",
    "intercom.io",
    "kargo.com",
    "krxd.net",
    "lijit.com",
    "liveintent.com",
    "liveramp.com",
    "mathtag.com",
    "media.net",
    "mediaplex.com",
    "moatads.com",
    "mookie1.com",
    "nexage.com",
    "openx.net",
    "outbrain.com",
    "owneriq.net",
    "pubmatic.com",
    "quantserve.com",
    "revcontent.com",
    "rubiconproject.com",
    "serving-sys.com",
    "sharethrough.com",
    "smaato.net",
    "smartadserver.com",
    "spotxchange.com",
    "taboola.com",
    "tapad.com",
    "tidaltv.com",
    "tribalfusion.com",
    "turn.com",
    "undertone.com",
    "yieldmo.com",
    // Analytics/Tracking
    "mixpanel.com",
    "segment.io",
    "segment.com",
    "amplitude.com",
    "heap.io",
    "hotjar.com",
    "fullstory.com",
    "mouseflow.com",
    "crazyegg.com",
    "clicktale.com",
    "kissmetrics.com",
    "chartbeat.com",
    "newrelic.com",
    "nr-data.net",
    "omtrdc.net",
    "scorecardresearch.com",
    "quantcount.com",
    "comscore.com",
    // Social/Widget trackers
    "twitter.com/i/adsct",
    "platform.twitter.com",
    "platform.linkedin.com",
    "snap.licdn.com",
    "pinterest.com/ct",
    // CDN/Ad delivery
    "cloudfront.net/ads",
    "akamaihd.net/ads",
    "fastly.net/ads",
    // Popups/Malware
    "popads.net",
    "popcash.net",
    "propellerads.com",
    "revive-adserver.com",
    // Chinese ad networks
    "cnzz.com",
    "hm.baidu.com",
    "pos.baidu.com",
    "cpro.baidu.com",
    "tongji.baidu.com",
    "51.la",
    "tanx.com",
    "alimama.com",
    "mmstat.com",
    "irs01.com",
    "suning.com/ads",
    "qq.com/ads",
    "gtimg.cn/ads",
    // Email tracking
    "mailtrack.io",
    "bananatag.com",
    "yesware.com",
    // Misc trackers
    "bugsnag.com",
    "sentry.io",
    "rollbar.com",
    "raygun.io",
    "airbrake.io",
    "honeybadger.io",
    // Fingerprinting
    "fingerprintjs.com",
    "threatmetrix.com",
    "iovation.com",
    "sift.com",
    // Consent/CMP (often blocked)
    "quantcast.mgr.consensu.org",
    "trustarc.com",
    "onetrust.com",
    "cookiebot.com",
    "usercentrics.eu",
    // Video ads
    "jwpcdn.com/ads",
    "videoplaza.tv",
    "spotx.tv",
    "freewheel.tv",
    // Native ads
    "mgid.com",
    "zemanta.com",
    "nativo.com",
    "shareaholic.com",
    // Push notification spam
    "onesignal.com",
    "pushcrew.com",
    "pusher.com/ads",
    "gravitec.net",
    // Crypto miners
    "coinhive.com",
    "coin-hive.com",
    "cryptoloot.pro",
    "webminepool.com",
];
