[package]
name = "wisp-fetcher"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
browser = ["dep:wisp-browser"]
stealth = ["browser", "dep:wisp-stealth"]

[dependencies]
wisp-core = { workspace = true }
wisp-http = { workspace = true }
wisp-browser = { workspace = true, optional = true }
wisp-stealth = { workspace = true, optional = true }
tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
tracing = { workspace = true }
moka = { workspace = true }
chrono = { workspace = true }
parking_lot = { workspace = true }
wreq-util = { workspace = true }
wreq = { workspace = true }

[dev-dependencies]
wisp-parser = { workspace = true }
tempfile = { workspace = true }
