[package]
name = "wisp-browser"
version = "0.1.0"
edition = "2024"
rust-version = "1.91.1"
license = "Apache-2.0"

[dependencies]
wisp-core = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
tokio-tungstenite = { version = "0.30", features = ["rustls-tls-webpki-roots"] }
tungstenite = "0.30"
which = "7"
zip = "2"
tempfile = { workspace = true }
base64 = "0.22"
rand = { workspace = true }
futures = { workspace = true }
wreq = { workspace = true }
regex = { workspace = true }
url = { workspace = true }
tracing = { workspace = true }
