[package]
name = "wisp-core"
version = "0.1.0"
edition = "2024"
rust-version = "1.91.1"
license = "Apache-2.0"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = "2"
url = { workspace = true }
regex = { workspace = true }
tracing = { workspace = true }
rand = { workspace = true }
encoding_rs = "0.8"
